# CI with maven build and scan

name: CI docker build native amd64

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - graal
      - macos
  release:
    types: [published]

jobs:
  docker:
    runs-on: macos-14
    steps:

      - uses: actions/checkout@main
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: Echo ref name trigger
        run: echo ${{ github.ref_name }}

      - uses: graalvm/setup-graalvm@main
        with:
          java-version: '22-ea'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Cache Maven packages
        uses: actions/cache@main
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        run: mvn install -Dnative -Dquarkus.native.container-build=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        
      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          platforms: linux/arm64
          push: true
          tags: fugeritorg/fj-daogen-quarkus-demo:${{ github.ref_name }}-arm64native,fugeritorg/fj-daogen-quarkus-demo:latest-arm64native
